=== davidrlopez/HTML-CSS-Projects/XSD/TAREA 2 XSD/LM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:simpleType name="tipoRotulo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="a"/>
            <xs:enumeration value="b"/>
            <xs:enumeration value="c"/>
            <xs:enumeration value="d"/>
            <xs:enumeration value="e"/>
            <xs:enumeration value="f"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoDescripcionOpcion">
        <xs:restriction base="xs:string">
            <xs:maxLength value="200"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCorrecta">
        <xs:restriction base="xs:boolean">
            <xs:pattern value="true"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoOrden">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="999"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoPuntos">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="99.999"/>
            <xs:totalDigits value="5"/>
            <xs:fractionDigits value="3"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoIdEjercicio">
        <xs:restriction base="xs:ID">
            <xs:pattern value="P[1-9]E([1-9]|[1-9][0-9])"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="modulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="unidades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="unidad" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="test" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                    <xs:element name="opciones">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="opcion" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="rotulo"      type="tipoRotulo"           use="required"/>
                                                                        <xs:attribute name="descripcion" type="tipoDescripcionOpcion" use="required"/>
                                                                        <xs:attribute name="correcta"    type="tipoCorrecta"          use="optional"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id"    type="xs:ID"    use="required"/>
                                                <xs:attribute name="orden" type="tipoOrden" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id"     type="xs:ID"     use="required"/>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="prueba" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parte" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ejercicio" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="enunciado" type="xs:string"/>
                                                    <xs:element name="items" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="descripcion" type="xs:string"  use="required"/>
                                                                        <xs:attribute name="peso"        type="xs:integer" use="optional"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="anexos" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="anexo" minOccurs="1" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="src" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id"     type="tipoIdEjercicio" use="required"/>
                                                <xs:attribute name="puntos" type="tipoPuntos"      use="required"/>
                                                <xs:attribute name="unidad" type="xs:IDREF"        use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id"            type="xs:ID"      use="required"/>
                                    <xs:attribute name="titulo"        type="xs:string"  use="required"/>
                                    <xs:attribute name="tarea"         type="xs:anyURI"  use="optional"/>
                                    <xs:attribute name="puntos_totales" type="tipoPuntos" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id"     type="xs:ID"    use="required"/>
                        <xs:attribute name="titulo" type="xs:string" use="required"/>
                        <xs:attribute name="fecha"  type="xs:date"  use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id"     type="xs:ID"    use="required"/>
            <xs:attribute name="titulo" type="xs:string" use="required"/>
        </xs:complexType>

        <xs:key name="claveUnidad">
            <xs:selector xpath="unidades/unidad"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:keyref name="refEjercicioUnidad" refer="claveUnidad">
            <xs:selector xpath="prueba/parte/ejercicio"/>
            <xs:field xpath="@unidad"/>
        </xs:keyref>

    </xs:element>

</xs:schema>

=== davidrlopez/HTML-CSS-Projects/XSD/TAREA 2 XSD/LM.xml
<?xml version="1.0" encoding="UTF-8"?>
<modulo id="LM" titulo="Lenguajes de Marcas y SGI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LM.xsd"><!-- 1.1 Se enlaza correctamente para validación-->
    <unidades>
        <unidad id="UT1" nombre="XML" >
            <test id="T01001" orden="1">
                ¿Qué partes componen un elemento XML?
                <opciones>
                    <opcion rotulo="a" descripcion="Etiqueta, contenido de apertura y clausura y entidad" />
                    <opcion rotulo="b" descripcion="Etiquetas de apertura y clausura, contenido y atributos" correcta="true" />
                    <opcion rotulo="c" descripcion="Atributos, entidad de apertura y clausura y contenido" />
                    <opcion rotulo="d" descripcion="Entidades, relaciones y atributos de apertura y clausura" />
                </opciones>
            </test>
            <test id="T01002" orden="2">
                ¿Qué significa que un documento XML es válido?
                <opciones>
                    <opcion rotulo="a" descripcion="Que su sintaxis es correcta y puede leerse con un parser XML estándar" />
                    <opcion rotulo="b" descripcion="Que su contenido responde a unas especificaciones, aunque posea errores sintácticos" />
                    <opcion rotulo="c" descripcion="Que es sintácticamente correcto y además cumple unos requisitos respecto a su estructura y semántica" correcta="true" />
                    <opcion rotulo="d" descripcion="Todo lo del punto c y además una autoridad certificadora lo ha verificado y firmado digitalmente" />
                </opciones>
            </test>
        </unidad>
        <unidad id="UT2" nombre="HTML+CSS" />
        <unidad id="UT3" nombre="RSS+ATOM" />
        <unidad id="UT4" nombre="Validación" />
        <unidad id="UT5" nombre="XPath+XSLT" />
        <unidad id="UT6" nombre="XQuery" />
        <unidad id="UT7" nombre="SGI" />
    </unidades>
    <prueba id="P20220301" titulo="Final de marzo de 2022" fecha="2022-03-01">
        <parte id="P1" titulo="Recuperación 1"  tarea="https://ead.murciaeduca.es/mod/assign/view.php?id=699629" puntos_totales="10.0">
            <ejercicio id="P1E1" puntos="3.0" unidad="UT1">
                <enunciado>
                    Diseña un archivo XML que cumpla con las siguientes especificaciones: ...
                </enunciado>                    
                <items>
                        <item descripcion="El XML está bien formado" peso="30" />
                        <item descripcion="Estructura de nodos" peso="30" />
                        <item descripcion="Uso de atributos/valores" peso="20" />
                        <item descripcion="Datos de ejemplo" peso="20" />
                </items>
            </ejercicio>
            <ejercicio id="P1E2" puntos="2.5" unidad="UT2">
                <enunciado>
                    Diseña una página HTML como la que puede verse en la captura: ...
                </enunciado>                    
                <items>
                    <item descripcion="Corrección sintáctica" peso="20" />
                    <item descripcion="Estructura de capas" peso="30" />
                    <item descripcion="Etiquetas HTML5" peso="20" />
                    <item descripcion="Metadatos" peso="20" />
                    <item descripcion="Uso de entidades" peso="10" />
                </items>
                <anexos>
                    <anexo src="captura_p1e2.png"/>
                </anexos>
            </ejercicio>
            <ejercicio id="P1E3" puntos="2.5" unidad="UT2">
                <enunciado>
                    Desarrolla las reglas CSS para: ...
                </enunciado>                    
                <items>
                    <item descripcion="Regla 1"/>
                    <item descripcion="Regla 2"/>
                    <item descripcion="Regla 3"/>
                    <item descripcion="Regla 4"/>
                    <item descripcion="Regla 5"/>
                </items>
            </ejercicio>
            <ejercicio id="P1E4" puntos="2.0" unidad="UT3">
                <enunciado>
                    Crea un archivo RSS que responda a estos requisitos: ...
                </enunciado>                    
                <items>
                    <item descripcion="Requisito 1" />
                    <item descripcion="Requisito 2" />
                    <item descripcion="Requisito 3" />
                    <item descripcion="Requisito 4" />
                </items>
            </ejercicio>
        </parte>
    </prueba>
</modulo>
