=== davidrlopez/HTML-CSS-Projects/XSD/almacen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento raíz -->
  <xs:element name="almacen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="productos" type="Tproductos"/>
        <xs:element name="ubicaciones" type="Tubicaciones"/>
        <xs:element name="palets" type="Tpalets"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tipos para Productos -->
  <xs:complexType name="Tproductos">
    <xs:sequence>
      <xs:element name="producto" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required"/>
          <xs:attribute name="descripcion" type="xs:string" use="required"/>
          <xs:attribute name="valor_ud" type="xs:decimal" use="required"/>
          <xs:attribute name="unidades" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Tipos para Ubicaciones -->
  <xs:complexType name="Tubicaciones">
    <xs:sequence>
      <xs:element name="nave" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="sector" maxOccurs="unbounded">
              <xs:complexType mixed="true">
                <xs:attribute name="id" type="xs:string" use="required"/>
                <xs:attribute name="estado" type="xs:string" use="required"/>
                <xs:attribute name="capacidad" type="xs:integer" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Tipos para Palets -->
  <xs:complexType name="Tpalets">
    <xs:sequence>
      <xs:element name="palet" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="contenido" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="producto" type="xs:string" use="required"/>
                <xs:attribute name="cantidad" type="xs:integer" use="required"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required"/>
          <xs:attribute name="ubicacion" type="xs:string" use="optional"/>
          <xs:attribute name="verificado" type="xs:dateTime" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== davidrlopez/HTML-CSS-Projects/XSD/almacen.xml
<?xml version="1.0" encoding="UTF-8"?>
<almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="almacen.xsd">
  <productos>
    <producto id="GS001" descripcion="Golosina tipo 1" valor_ud="1.30" unidades="cajas" />
    <producto id="PR001" descripcion="Piruleta tipo 1" valor_ud="1.50" unidades="cajas" />
    <producto id="PS001" descripcion="Pistacho tipo 1" valor_ud="3.25" unidades="bolsas" />
  </productos>
  <ubicaciones>
    <nave id="NV001">
      <sector id="SC001001" estado="D" capacidad="3000" />
      <sector id="SC001002" estado="D" capacidad="2000" />
    </nave>
    <nave id="NV0002">
      <sector id="SC002001" estado="D" capacidad="2500" />
      <sector id="SC002002" estado="N"> En obras por reparaciones varias. </sector>
    </nave>
  </ubicaciones>
  <palets>
    <palet id="PL000001" ubicacion="SC001001" verificado="2019-01-15T17:45:00">
      <contenido producto="PS001" cantidad="400" />
      <observaciones>Presenta rotura en una de las bolsas</observaciones>
    </palet>
    <palet id="PL000002">
      <contenido producto="GS001" cantidad="40" />
      <contenido producto="PR001" cantidad="60" />
    </palet>
  </palets>
</almacen>
